name: araimox
description: A modern sports streaming application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # Video Player & UI
  video_player: ^2.8.2
  chewie: ^1.7.5
  # Networking
  http: ^1.2.0
  # UI Utilities
  marquee: ^2.2.3
  google_fonts: ^6.1.0
  provider: ^6.1.1
  cached_network_image: ^3.3.1
  # To keep screen on during playback
  wakelock_plus: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
