name: araimox
description: A modern sports streaming application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # UI & Icons
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  marquee: ^2.2.3
  
  # Video Player (ExoPlayer)
  video_player: ^2.8.2
  chewie: ^1.7.5
  wakelock_plus: ^1.1.4
  
  # Network & Data
  http: ^1.2.0
  cached_network_image: ^3.3.1
  provider: ^6.1.1
  
  # Utilities
  url_launcher: ^6.2.4
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
